### ISSUE TITLE
Release kntnr 0.4.4

### ISSUE THREAD

**Issue by yutannihilation** [yutannihilation/kntnr#14]
Prepare for release: 
 
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_kntnr.html) 
* [x] `devtools::check(remote = TRUE, manual = TRUE)` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [x] `revdepcheck::revdep_check(num_workers = 4)` 
* [x] Update `cran-comments.md` 
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('patch')` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [x] `usethis::use_dev_version()`

**Comment by ayukakoi** [comment]
例えば、下記のようにPowerBI上でレコード取得すると
kntn_records(app = 123, max_records = 400, records_per_request = 200)
KINTONE上でチェックボックス項目、添付ファイル項目、組織選択項目がERRORとなります。
原因はPowerBI側の問題でしょうか?

**Comment by yutannihilation** [comment]
どのようなエラーが出るでしょうか？
このパッケージを作ったのは2年前なので、最新のAPIに追随できていないかもしれません。

**Comment by ayukakoi** [comment]
PowerBI上で｢データの更新｣を実行すると、正常に件数が読み込まれますが、エラーがありますとなり、PowerQueryエディターを確認すると、KINTONE上でチェックボックス項目、添付ファイル項目、組織選択項目がすべての行でERRORとなっています。
PowerBI側では、｢DataFormat.Error: この値は、.RData 形式からは変換できません。｣となります。

**Comment by yutannihilation** [comment]
なるほど、PowerBI使ったことないんですがそれはPowerBI側のエラーだとおもいます！

**Comment by yutannihilation** [comment]
たぶん対応していないデータ形式なんじゃないかなと。

**Comment by ayukakoi** [comment]
ご連絡ありがとうございます。
承知しました。
当方側でデータ型などもう一度確認してみたいと思います。
