### ISSUE TITLE
kntn_recordsがlist形式で500レコード以上出力できない

### ISSUE THREAD

**Issue by kesuko** [yutannihilation/kntnr#17]
kntn_records(バージョン0.4.4)を利用しておりますが、以下のように指定したところ、
 レコード200までしか出力されません。

 mlist <- kntn_records(app = 47, fields="シリアルナンバー,投入日,出荷日,
 完了日",max_records = 3000, records_per_request = 200, as ="list")

 Getting 200 records from 0

 list形式でない場合（data.frame）は、以下のように200レコード以上取り込まれます。
 
Getting 200 records from 0
 Getting 200 records from 200

 list形式の出力で500レコード以上を出力することはできるのでしょうか。

**Comment by yutannihilation** [comment]
ご報告ありがとうございます。コードを確認したところ、おそらくこのループを抜ける処理の部分が間違っているのだと思いますが、私はkintoneを触れる環境になく修正が難しいです、すみません。。

https://github.com/yutannihilation/kntnr/blob/16555e9a4cd91283c249ca97e1bc01470e729070/R/kntn_record.R#L210

お手数なのですが、以下のように200レコードずつoffsetを指定して結果を取得し、そちらを結合していただくとうまくいくかと思います。

``` r
kntn_records_wrapper <- function(offset) {
  mlist <- kntn_records(
    app = 47,
    fields = "シリアルナンバー,投入日,出荷日,完了日",
    max_records = 3000,
    offset = offset,
    records_per_request = 200,
    as ="list"
)

offsets <- seq(0, 3000, by = 200)
result <- lapply(offsets, kntn_records_wrapper)
```

**Comment by kesuko** [comment]
情報ありがとうございました！オフセットをなめる分、空のデータができるのでデータのクリーニングが必要となりましたが
なんとかなりそうです。

**Comment by yutannihilation** [comment]
ありがとうございます、なんとかなりそうでよかったです！
